language: csharp
solution: DnDGen.Infrastructure.sln
mono: none
dotnet: 3.1

script:
  - dotnet build DnDGen.Infrastructure.sln -c Release
    && dotnet test ./DnDGen.Infrastructure.Tests.Unit/DnDGen.Infrastructure.Tests.Unit.csproj -v normal
    && dotnet test ./DnDGen.Infrastructure.Tests.Integration/DnDGen.Infrastructure.Tests.Integration.csproj -v normal
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master
matrix:
  fast_finish: true
